/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class ItemUsuario extends javax.swing.JPanel {
    
   
   

    /**
     * Creates new form ItemUsuario
     */
    public ItemUsuario() {
       
      
        initComponents();
      
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonUsuarioLista = new javax.swing.JButton();
        buttonUsuarioNuevo = new javax.swing.JButton();
        buttonUsuarioEditar1 = new javax.swing.JButton();
        buttonUsuarioEliminar1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(750, 634));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(670, 70));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonUsuarioLista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonUsuarioLista.setForeground(new java.awt.Color(255, 255, 255));
        buttonUsuarioLista.setText("Lista Usuario");
        buttonUsuarioLista.setBorder(null);
        buttonUsuarioLista.setContentAreaFilled(false);
        jPanel1.add(buttonUsuarioLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, 50));

        buttonUsuarioNuevo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonUsuarioNuevo.setForeground(new java.awt.Color(255, 255, 255));
        buttonUsuarioNuevo.setText("Nuevo Usuario");
        buttonUsuarioNuevo.setBorder(null);
        buttonUsuarioNuevo.setContentAreaFilled(false);
        buttonUsuarioNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsuarioNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(buttonUsuarioNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, -1, 40));

        buttonUsuarioEditar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonUsuarioEditar1.setForeground(new java.awt.Color(255, 255, 255));
        buttonUsuarioEditar1.setText("Editar Usuario");
        buttonUsuarioEditar1.setBorder(null);
        buttonUsuarioEditar1.setContentAreaFilled(false);
        buttonUsuarioEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsuarioEditar1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonUsuarioEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, 50));

        buttonUsuarioEliminar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonUsuarioEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        buttonUsuarioEliminar1.setText("Eliminar Usuario");
        buttonUsuarioEliminar1.setBorder(null);
        buttonUsuarioEliminar1.setContentAreaFilled(false);
        jPanel1.add(buttonUsuarioEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 50));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 10, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 10, 30));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 10, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\UNIVERSIDAD\\interfaz\\itemhorizontal2.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        content.setOpaque(false);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 750, 596));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUsuarioNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsuarioNuevoActionPerformed
        
        vendedorNuevoCliente usuarioNuevo =new vendedorNuevoCliente();
        usuarioNuevo.setSize(750,525);
        usuarioNuevo.setLocation(0, 0);
        
        content.removeAll();
        content.add(usuarioNuevo,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }//GEN-LAST:event_buttonUsuarioNuevoActionPerformed

    private void buttonUsuarioEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsuarioEditar1ActionPerformed
        
        VendedorEditarCliente usuarioEditar = new VendedorEditarCliente(); 
        usuarioEditar.setSize(750,525);
        usuarioEditar.setLocation(0, 0);
        
        content.removeAll();
        content.add(usuarioEditar,BorderLayout.CENTER);
        content.revalidate();
        content.repaint(); 
    }//GEN-LAST:event_buttonUsuarioEditar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonUsuarioEditar1;
    private javax.swing.JButton buttonUsuarioEliminar1;
    private javax.swing.JButton buttonUsuarioLista;
    private javax.swing.JButton buttonUsuarioNuevo;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
    
    



}
