/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

/**
 *
 * @author ASUS
 */
public class ItemHistorialMantenimiento extends javax.swing.JPanel {

    /**
     * Creates new form ItemHIstorialMantenimiento
     */
    public ItemHistorialMantenimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonId = new javax.swing.JButton();
        buttonFecha = new javax.swing.JButton();
        buttonMarca = new javax.swing.JButton();
        buttonDescripcion = new javax.swing.JButton();
        buttonModelo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonId.setForeground(new java.awt.Color(255, 255, 255));
        buttonId.setText("Id");
        buttonId.setBorder(null);
        buttonId.setContentAreaFilled(false);
        buttonId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIdActionPerformed(evt);
            }
        });
        jPanel1.add(buttonId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 50));

        buttonFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonFecha.setForeground(new java.awt.Color(255, 255, 255));
        buttonFecha.setText("Fecha");
        buttonFecha.setBorder(null);
        buttonFecha.setContentAreaFilled(false);
        buttonFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFechaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 130, 50));

        buttonMarca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonMarca.setForeground(new java.awt.Color(255, 255, 255));
        buttonMarca.setText("Marca");
        buttonMarca.setBorder(null);
        buttonMarca.setContentAreaFilled(false);
        jPanel1.add(buttonMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 0, 100, 50));

        buttonDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        buttonDescripcion.setText("Descripcion");
        buttonDescripcion.setBorder(null);
        buttonDescripcion.setContentAreaFilled(false);
        jPanel1.add(buttonDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 120, 50));

        buttonModelo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonModelo.setForeground(new java.awt.Color(255, 255, 255));
        buttonModelo.setText("Modelo");
        buttonModelo.setBorder(null);
        buttonModelo.setContentAreaFilled(false);
        jPanel1.add(buttonModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 80, 50));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 10, 30));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 20, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 20, 30));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 20, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\GitHub\\7502320048_Shein_moreno_POO-_2024_1\\7502320048_Shein_moreno_POO_ACT_1 _2024\\SheinMorenoAct1Poo20241\\src\\Interfaces\\itemhorizontal2.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 55));

        content.setOpaque(false);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 750, 596));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIdActionPerformed

        
    }//GEN-LAST:event_buttonIdActionPerformed

    private void buttonFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFechaActionPerformed

        
    }//GEN-LAST:event_buttonFechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDescripcion;
    private javax.swing.JButton buttonFecha;
    private javax.swing.JButton buttonId;
    private javax.swing.JButton buttonMarca;
    private javax.swing.JButton buttonModelo;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
