/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class ItemUsuario extends javax.swing.JPanel {
    
   
   

    /**
     * Creates new form ItemUsuario
     */
    public ItemUsuario() {
       
      
        initComponents();
      
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonClienteLista = new javax.swing.JButton();
        buttonClienteNuevo = new javax.swing.JButton();
        buttonClienteEditar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(753, 634));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(670, 70));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonClienteLista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonClienteLista.setForeground(new java.awt.Color(255, 255, 255));
        buttonClienteLista.setText("Lista ");
        buttonClienteLista.setBorder(null);
        buttonClienteLista.setContentAreaFilled(false);
        buttonClienteLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClienteListaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonClienteLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 50));

        buttonClienteNuevo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonClienteNuevo.setForeground(new java.awt.Color(255, 255, 255));
        buttonClienteNuevo.setText("Nuevo ");
        buttonClienteNuevo.setBorder(null);
        buttonClienteNuevo.setContentAreaFilled(false);
        buttonClienteNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClienteNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(buttonClienteNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 50));

        buttonClienteEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonClienteEditar.setForeground(new java.awt.Color(255, 255, 255));
        buttonClienteEditar.setText("Editar ");
        buttonClienteEditar.setBorder(null);
        buttonClienteEditar.setContentAreaFilled(false);
        buttonClienteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClienteEditarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonClienteEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, 50));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 10, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 10, 30));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 10, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\UNIVERSIDAD\\interfaz\\itemhorizontal2.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        content.setOpaque(false);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 750, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClienteNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClienteNuevoActionPerformed
        
        vendedorNuevoCliente clienteNuevo =new vendedorNuevoCliente();
        clienteNuevo.setSize(750,525);
        clienteNuevo.setLocation(0, 0);
        
        content.removeAll();
        content.add(clienteNuevo,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }//GEN-LAST:event_buttonClienteNuevoActionPerformed

    private void buttonClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClienteEditarActionPerformed
        
        VendedorEditarCliente clienteEditar = new VendedorEditarCliente(); 
        clienteEditar.setSize(750,525);
        clienteEditar.setLocation(0, 0);
        
        content.removeAll();
        content.add(clienteEditar,BorderLayout.CENTER);
        content.revalidate();
        content.repaint(); 
    }//GEN-LAST:event_buttonClienteEditarActionPerformed

    private void buttonClienteListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClienteListaActionPerformed
        
        VendedorListaCliente clienteLista = new VendedorListaCliente(); 
        clienteLista.setSize(750,525);
        clienteLista.setLocation(0, 0);
        
        content.removeAll();
        content.add(clienteLista,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_buttonClienteListaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClienteEditar;
    private javax.swing.JButton buttonClienteLista;
    private javax.swing.JButton buttonClienteNuevo;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
    
    



}
