/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import java.awt.BorderLayout;

/**
 *
 * @author ASUS
 */
public class ItemPagoEnLinea extends javax.swing.JPanel {

    /**
     * Creates new form ItemHIstorialMantenimiento
     */
    public ItemPagoEnLinea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button_lista = new javax.swing.JButton();
        buttton_pago = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        panel_pagoeEnLinea = new javax.swing.JPanel();

        setOpaque(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_lista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button_lista.setForeground(new java.awt.Color(255, 255, 255));
        button_lista.setText("Lista");
        button_lista.setBorder(null);
        button_lista.setContentAreaFilled(false);
        button_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_listaActionPerformed(evt);
            }
        });
        jPanel1.add(button_lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 130, 50));

        buttton_pago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttton_pago.setForeground(new java.awt.Color(255, 255, 255));
        buttton_pago.setText("Pago");
        buttton_pago.setBorder(null);
        buttton_pago.setContentAreaFilled(false);
        buttton_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttton_pagoActionPerformed(evt);
            }
        });
        jPanel1.add(buttton_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 50));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 10, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\UNIVERSIDAD\\interfaz\\itemhorizontal2.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 55));

        content.setOpaque(false);

        panel_pagoeEnLinea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_pagoeEnLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_pagoeEnLinea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 750, 596));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_listaActionPerformed

        ListaPagoEnLinea lista_pago =new ListaPagoEnLinea();
        lista_pago.setSize(750,525);
        lista_pago.setLocation(0, 0);
        
        content.removeAll();
        content.add(lista_pago,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_button_listaActionPerformed

    private void buttton_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttton_pagoActionPerformed
        
        ventanaPagoEnLinea pago_linea =new ventanaPagoEnLinea();
        pago_linea.setSize(750,525);
        pago_linea.setLocation(0, 0);
        
        content.removeAll();
        content.add(pago_linea,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_buttton_pagoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_lista;
    private javax.swing.JButton buttton_pago;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panel_pagoeEnLinea;
    // End of variables declaration//GEN-END:variables
}
