/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import com.mysql.jdbc.ResultSetInternalMethods;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.SwingUtilities;
import java.sql.SQLException;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class VendedorEditarCliente extends javax.swing.JPanel {

    /**
     * Creates new form VendedorEditarcliente
     */
    public VendedorEditarCliente() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editarCliente = new javax.swing.JLabel();
        dni1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        apellido1 = new javax.swing.JLabel();
        celular1 = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        buscar = new javax.swing.JLabel();
        buttonGuardarCambiosCliente = new javax.swing.JButton();
        text_id = new javax.swing.JTextField();
        text_apellido = new javax.swing.JTextField();
        text_nombre = new javax.swing.JTextField();
        text_correoElectronico = new javax.swing.JTextField();
        text_celular = new javax.swing.JTextField();
        text_direccion = new javax.swing.JTextField();
        text_buscar = new javax.swing.JTextField();
        text_contraseña = new javax.swing.JTextField();
        button_buscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editarCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editarCliente.setForeground(new java.awt.Color(59, 75, 82));
        editarCliente.setText("Editar Cliente");
        jPanel1.add(editarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 219, -1));

        dni1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dni1.setForeground(new java.awt.Color(59, 75, 82));
        dni1.setText("Id:");
        jPanel1.add(dni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(59, 75, 82));
        nombre.setText("Nombres:");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        correo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        correo.setForeground(new java.awt.Color(59, 75, 82));
        correo.setText("Correo:");
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 68, -1));

        apellido1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        apellido1.setForeground(new java.awt.Color(59, 75, 82));
        apellido1.setText("Apellidos:");
        jPanel1.add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 80, -1));

        celular1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        celular1.setForeground(new java.awt.Color(59, 75, 82));
        celular1.setText("Celular:");
        jPanel1.add(celular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 63, -1));

        direccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        direccion.setForeground(new java.awt.Color(59, 75, 82));
        direccion.setText("Direccion:");
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 97, -1));

        contraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contraseña.setForeground(new java.awt.Color(59, 75, 82));
        contraseña.setText("Contraseña:");
        jPanel1.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 110, -1));

        buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(59, 75, 82));
        buscar.setText("Buscar:");
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 40, 70, -1));

        buttonGuardarCambiosCliente.setBackground(new java.awt.Color(0, 150, 247));
        buttonGuardarCambiosCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonGuardarCambiosCliente.setForeground(new java.awt.Color(255, 255, 255));
        buttonGuardarCambiosCliente.setText("Guardar Cambios");
        buttonGuardarCambiosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarCambiosClienteActionPerformed(evt);
            }
        });
        jPanel1.add(buttonGuardarCambiosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 354, 45));

        text_id.setBorder(null);
        jPanel1.add(text_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 258, -1));

        text_apellido.setBorder(null);
        text_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_apellidoActionPerformed(evt);
            }
        });
        jPanel1.add(text_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, -1));

        text_nombre.setBorder(null);
        text_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(text_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 258, -1));

        text_correoElectronico.setBorder(null);
        jPanel1.add(text_correoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 279, -1));

        text_celular.setBorder(null);
        text_celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_celularActionPerformed(evt);
            }
        });
        jPanel1.add(text_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 279, -1));

        text_direccion.setBorder(null);
        text_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_direccionActionPerformed(evt);
            }
        });
        jPanel1.add(text_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 621, -1));

        text_buscar.setBorder(null);
        text_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(text_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 210, -1));

        text_contraseña.setBorder(null);
        text_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_contraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(text_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 280, -1));

        button_buscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\GitHub\\7502320048_Shein_moreno_POO-_2024_1\\7502320048_Shein_moreno_POO_ACT_1 _2024\\SheinMorenoAct1Poo20241\\src\\Interfaces\\iconos\\lupa.png")); // NOI18N
        button_buscar.setBorder(null);
        button_buscar.setBorderPainted(false);
        button_buscar.setContentAreaFilled(false);
        button_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(button_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 258, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 258, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 280, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 220, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 279, 11));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 621, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 260, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 279, 10));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\UNIVERSIDAD\\interfaz\\contentBlanco.png")); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGuardarCambiosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarCambiosClienteActionPerformed
        modificarInformacionCliente();
    }//GEN-LAST:event_buttonGuardarCambiosClienteActionPerformed

    private void text_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_apellidoActionPerformed

    private void text_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nombreActionPerformed

    private void text_celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_celularActionPerformed

    private void text_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_direccionActionPerformed

    private void text_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_buscarActionPerformed

    private void text_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_contraseñaActionPerformed

    private void button_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_buscarActionPerformed

        botonBuscar();


    }//GEN-LAST:event_button_buscarActionPerformed

    private boolean botonBuscar() {

        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/plataforma", "root", "");
            PreparedStatement preparedStatement = connection.prepareStatement("select * from cliente where ID = ?");
            preparedStatement.setString(1, text_buscar.getText().trim());

            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                text_id.setText(resultSet.getString("ID"));
                text_nombre.setText(resultSet.getString("Nombre"));
                text_apellido.setText(resultSet.getString("Apellido"));
                text_celular.setText(resultSet.getString("Celular"));
                text_correoElectronico.setText(resultSet.getString("Correo"));
                text_direccion.setText(resultSet.getString("Direccion"));
                text_contraseña.setText(resultSet.getString("Contraseña"));

            } else {
                JOptionPane.showMessageDialog(null, "Cliente no registrado");

            }

        } catch (Exception e) {

        }
        return false;
    }

    private void modificarInformacionCliente() {
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/plataforma", "root", "");
            PreparedStatement preparedStatement = connection.prepareStatement("UPDATE cliente SET ID = ?, Nombre = ?, Apellido = ?, Celular = ?, Correo = ?, Direccion = ?, Contraseña = ?");
            preparedStatement.setString(1, text_id.getText().trim());
            preparedStatement.setString(2, text_nombre.getText().trim());
            preparedStatement.setString(3, text_apellido.getText().trim());
            preparedStatement.setString(4, text_celular.getText().trim());
            preparedStatement.setString(5, text_correoElectronico.getText().trim());
            preparedStatement.setString(6, text_direccion.getText().trim());
            preparedStatement.setString(7, text_contraseña.getText().trim());
            
           preparedStatement.executeUpdate();
           JOptionPane.showMessageDialog(this, "Información actualizada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al actualizar la información", "Error", JOptionPane.ERROR_MESSAGE);

        }
       

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido1;
    private javax.swing.JLabel buscar;
    private javax.swing.JButton buttonGuardarCambiosCliente;
    private javax.swing.JButton button_buscar;
    private javax.swing.JLabel celular1;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel dni1;
    private javax.swing.JLabel editarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField text_apellido;
    private javax.swing.JTextField text_buscar;
    private javax.swing.JTextField text_celular;
    private javax.swing.JTextField text_contraseña;
    private javax.swing.JTextField text_correoElectronico;
    private javax.swing.JTextField text_direccion;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_nombre;
    // End of variables declaration//GEN-END:variables
}
