/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class VendedorCatalogo extends javax.swing.JPanel {

    /**
     * Creates new form ItemCatalogo
     */
    public VendedorCatalogo() {
        initComponents();
        table_catalogo.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        table_catalogo.getTableHeader().setOpaque(false);
        table_catalogo.getTableHeader().setBackground(new Color(32, 136, 203));
        table_catalogo.getTableHeader().setForeground(new Color(255, 255, 255));
        table_catalogo.setRowHeight(25);

        // Deshabilitar reordenación de columnas
        table_catalogo.getTableHeader().setReorderingAllowed(false);

        // Deshabilitar edición de celdas
        table_catalogo.setDefaultEditor(Object.class, null);

        cargarDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_catalogo = new javax.swing.JTable();
        buscar = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        button_buscar = new javax.swing.JButton();
        text_buscar = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_catalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Marca", "Modelo", "Cilindrada", "valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_catalogo.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(table_catalogo);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 720, 490));

        buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(59, 75, 82));
        buscar.setText("Buscar:");
        jPanel2.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 70, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 220, 10));

        button_buscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\GitHub\\7502320048_Shein_moreno_POO-_2024_1\\7502320048_Shein_moreno_POO_ACT_1 _2024\\SheinMorenoAct1Poo20241\\src\\Interfaces\\iconos\\lupa.png")); // NOI18N
        button_buscar.setBorder(null);
        button_buscar.setBorderPainted(false);
        button_buscar.setContentAreaFilled(false);
        button_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_buscarActionPerformed(evt);
            }
        });
        jPanel2.add(button_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        text_buscar.setBorder(null);
        text_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_buscarActionPerformed(evt);
            }
        });
        jPanel2.add(text_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_buscarActionPerformed

         String ID = text_buscar.getText().trim();
         buscarCatalogo(ID);
    }//GEN-LAST:event_button_buscarActionPerformed

    private void text_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_buscarActionPerformed

    private void buscarCatalogo(String ID) {
        try {
            Connection conexion = VendedorListaCliente.ConexionBD.conectar();
            PreparedStatement pst = conexion.prepareStatement("SELECT * FROM catalogo WHERE ID = ?");
            pst.setString(1, ID);
            ResultSet rs = pst.executeQuery();

            DefaultTableModel modelo = (DefaultTableModel) table_catalogo.getModel();
            modelo.setRowCount(0); // Limpiar la tabla antes de agregar nuevos datos

            if (rs.next()) {
                Object[] fila = {
                    rs.getString("ID"),
                    rs.getString("Marca"),
                    rs.getString("Modelo"),
                    rs.getString("Cilindrada"),
                    rs.getString("Valor"),
                    
                };
                modelo.addRow(fila);
            } else {
                JOptionPane.showMessageDialog(this, "Automivil no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
            }

            conexion.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public class ConexionBD {
        //BD bade de datos

        private static final String URL = "jdbc:mysql://localhost/plataforma";
        private static final String USER = "root";
        private static final String PASSWORD = "";

        public static Connection conectar() throws SQLException {
            return DriverManager.getConnection(URL, USER, PASSWORD);
        }
    }

    public static void main(String[] args) {

    }

    private void cargarDatos() {
        try {
            Connection conexion = VendedorListaCliente.ConexionBD.conectar();
            PreparedStatement pst = conexion.prepareStatement("SELECT * FROM catalogo");
            ResultSet rs = pst.executeQuery();

            DefaultTableModel modelo = (DefaultTableModel) table_catalogo.getModel();
            modelo.setRowCount(0); // Limpiar la tabla antes de agregar nuevos datos

            while (rs.next()) {
                Object[] fila = {
                    rs.getString("ID"),
                    rs.getString("Marca"),
                    rs.getString("Modelo"),
                    rs.getString("Cilindrada"),
                    rs.getString("Valor"),
                    

                };
                modelo.addRow(fila);
            }

            conexion.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscar;
    private javax.swing.JButton button_buscar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable table_catalogo;
    private javax.swing.JTextField text_buscar;
    // End of variables declaration//GEN-END:variables
}
