/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

/**
 *
 * @author ASUS
 */
public class VendedorEditarCliente extends javax.swing.JPanel {

    /**
     * Creates new form VendedorEditarcliente
     */
    public VendedorEditarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editarCliente = new javax.swing.JLabel();
        dni1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        apellido1 = new javax.swing.JLabel();
        celular1 = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        buscar = new javax.swing.JLabel();
        buttonGuardarCambiosCliente = new javax.swing.JButton();
        DNI = new javax.swing.JTextField();
        apellidos = new javax.swing.JTextField();
        nombres1 = new javax.swing.JTextField();
        correoElectronico = new javax.swing.JTextField();
        cedula1 = new javax.swing.JTextField();
        apellidos1 = new javax.swing.JTextField();
        buscarCliente = new javax.swing.JTextField();
        contraseñaText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editarCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editarCliente.setForeground(new java.awt.Color(59, 75, 82));
        editarCliente.setText("Editar Cliente");
        jPanel1.add(editarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 219, -1));

        dni1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dni1.setForeground(new java.awt.Color(59, 75, 82));
        dni1.setText("DNI:");
        jPanel1.add(dni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(59, 75, 82));
        nombre.setText("Nombres:");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        correo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        correo.setForeground(new java.awt.Color(59, 75, 82));
        correo.setText("Correo:");
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 68, -1));

        apellido1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        apellido1.setForeground(new java.awt.Color(59, 75, 82));
        apellido1.setText("Apellidos:");
        jPanel1.add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 80, -1));

        celular1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        celular1.setForeground(new java.awt.Color(59, 75, 82));
        celular1.setText("Celular:");
        jPanel1.add(celular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 63, -1));

        direccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        direccion.setForeground(new java.awt.Color(59, 75, 82));
        direccion.setText("Direccion:");
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 97, -1));

        contraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contraseña.setForeground(new java.awt.Color(59, 75, 82));
        contraseña.setText("Contraseña:");
        jPanel1.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 110, -1));

        buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(59, 75, 82));
        buscar.setText("Buscar:");
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 40, 70, -1));

        buttonGuardarCambiosCliente.setBackground(new java.awt.Color(0, 150, 247));
        buttonGuardarCambiosCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonGuardarCambiosCliente.setForeground(new java.awt.Color(255, 255, 255));
        buttonGuardarCambiosCliente.setText("Guardar Cambios");
        buttonGuardarCambiosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarCambiosClienteActionPerformed(evt);
            }
        });
        jPanel1.add(buttonGuardarCambiosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 354, 45));

        DNI.setBorder(null);
        jPanel1.add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 258, -1));

        apellidos.setBorder(null);
        apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosActionPerformed(evt);
            }
        });
        jPanel1.add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, -1));

        nombres1.setBorder(null);
        nombres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombres1ActionPerformed(evt);
            }
        });
        jPanel1.add(nombres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 258, -1));

        correoElectronico.setBorder(null);
        jPanel1.add(correoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 279, -1));

        cedula1.setBorder(null);
        cedula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedula1ActionPerformed(evt);
            }
        });
        jPanel1.add(cedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 279, -1));

        apellidos1.setBorder(null);
        apellidos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidos1ActionPerformed(evt);
            }
        });
        jPanel1.add(apellidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 621, -1));

        buscarCliente.setBorder(null);
        buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(buscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 140, -1));

        contraseñaText.setBorder(null);
        contraseñaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaTextActionPerformed(evt);
            }
        });
        jPanel1.add(contraseñaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 258, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 258, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 280, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 140, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 279, 11));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 621, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 260, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 279, 10));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\UNIVERSIDAD\\interfaz\\contentBlanco.png")); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGuardarCambiosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarCambiosClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGuardarCambiosClienteActionPerformed

    private void apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosActionPerformed

    private void nombres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombres1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombres1ActionPerformed

    private void cedula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedula1ActionPerformed

    private void apellidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidos1ActionPerformed

    private void buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarClienteActionPerformed

    private void contraseñaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DNI;
    private javax.swing.JLabel apellido1;
    private javax.swing.JTextField apellidos;
    private javax.swing.JTextField apellidos1;
    private javax.swing.JLabel buscar;
    private javax.swing.JTextField buscarCliente;
    private javax.swing.JButton buttonGuardarCambiosCliente;
    private javax.swing.JTextField cedula1;
    private javax.swing.JLabel celular1;
    private javax.swing.JLabel contraseña;
    private javax.swing.JTextField contraseñaText;
    private javax.swing.JLabel correo;
    private javax.swing.JTextField correoElectronico;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel dni1;
    private javax.swing.JLabel editarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombres1;
    // End of variables declaration//GEN-END:variables
}
