/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class VendedorNuevaVenta extends javax.swing.JPanel {

    /**
     * Creates new form VentanaNuevaVenta
     */
    public VendedorNuevaVenta() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        datosDelCliente = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        text_id = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Nombre = new javax.swing.JLabel();
        text_nombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Correo = new javax.swing.JLabel();
        text_correoElectronico = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Apellido = new javax.swing.JLabel();
        text_apellido = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Celular = new javax.swing.JLabel();
        text_celular = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Direccion = new javax.swing.JLabel();
        text_direccion = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        nuevaVenta1 = new javax.swing.JLabel();
        crearVenta = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        ID = new javax.swing.JLabel();
        text_idVehiculo = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        Modelo = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        Marca = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        CIlindrada = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        text_valor = new javax.swing.JTextField();
        Valor = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        datosDelVehiculo1 = new javax.swing.JLabel();
        Color2 = new javax.swing.JLabel();
        obcionesAdicionales1 = new javax.swing.JLabel();
        FechaEntregaVehiculoUsado = new javax.swing.JLabel();
        aireAcondicionadoNo = new javax.swing.JCheckBox();
        aireAcondicionadoSi2 = new javax.swing.JCheckBox();
        jSeparator17 = new javax.swing.JSeparator();
        tipoDePintura = new javax.swing.JLabel();
        obcionesAdicionales4 = new javax.swing.JLabel();
        ModeloVehiculoUsado = new javax.swing.JLabel();
        modeloVehiculoUsado = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        MarcaVehiculoUsado = new javax.swing.JLabel();
        marcaVehiculoUsado = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        CIlindradaVehiculoUsado = new javax.swing.JLabel();
        cilindradaVehiculoUsado = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        PrecioTasacion = new javax.swing.JLabel();
        precioTasacion = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        Matricula = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        fechaEntrega = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        FechaVenta = new javax.swing.JLabel();
        fechaEntrega1 = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        Garantia = new javax.swing.JLabel();
        garantia = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        buscar = new javax.swing.JLabel();
        text_buscar = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        button_buscar = new javax.swing.JButton();
        buscar1 = new javax.swing.JLabel();
        jSeparator30 = new javax.swing.JSeparator();
        button_buscar2 = new javax.swing.JButton();
        text_buscar1 = new javax.swing.JTextField();
        comboBox_modelo = new javax.swing.JComboBox<>();
        comboBox_marca = new javax.swing.JComboBox<>();
        comboBox_cilindrada = new javax.swing.JComboBox<>();
        pinturaMetalizadaSi = new javax.swing.JCheckBox();
        pinturaMetalizadaNo = new javax.swing.JCheckBox();
        fondo = new javax.swing.JLabel();

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datosDelCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        datosDelCliente.setForeground(new java.awt.Color(59, 75, 82));
        datosDelCliente.setText("Datos del Cliente");
        jPanel1.add(datosDelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 219, -1));

        Id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Id.setForeground(new java.awt.Color(59, 75, 82));
        Id.setText("Id:");
        jPanel1.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        text_id.setBorder(null);
        jPanel1.add(text_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 258, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 258, 10));

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(59, 75, 82));
        Nombre.setText("Nombres:");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 80, -1));

        text_nombre.setBorder(null);
        text_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(text_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 258, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 258, 10));

        Correo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Correo.setForeground(new java.awt.Color(59, 75, 82));
        Correo.setText("Correo:");
        jPanel1.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 68, -1));

        text_correoElectronico.setBorder(null);
        jPanel1.add(text_correoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 279, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 279, 10));

        Apellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Apellido.setForeground(new java.awt.Color(59, 75, 82));
        Apellido.setText("Apellidos:");
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, -1));

        text_apellido.setBorder(null);
        text_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_apellidoActionPerformed(evt);
            }
        });
        jPanel1.add(text_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 260, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 260, 10));

        Celular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Celular.setForeground(new java.awt.Color(59, 75, 82));
        Celular.setText("Celular:");
        jPanel1.add(Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 63, -1));

        text_celular.setBorder(null);
        text_celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_celularActionPerformed(evt);
            }
        });
        jPanel1.add(text_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 279, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 279, 11));

        Direccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Direccion.setForeground(new java.awt.Color(59, 75, 82));
        Direccion.setText("Direccion:");
        jPanel1.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 97, -1));

        text_direccion.setBorder(null);
        text_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_direccionActionPerformed(evt);
            }
        });
        jPanel1.add(text_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 621, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 621, 10));

        nuevaVenta1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nuevaVenta1.setForeground(new java.awt.Color(59, 75, 82));
        nuevaVenta1.setText("Nueva venta");
        jPanel1.add(nuevaVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 219, -1));

        crearVenta.setBackground(new java.awt.Color(0, 150, 247));
        crearVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        crearVenta.setForeground(new java.awt.Color(255, 255, 255));
        crearVenta.setText("Crear Venta");
        crearVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearVentaActionPerformed(evt);
            }
        });
        jPanel1.add(crearVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1780, 354, 45));

        jSeparator8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1530, 750, 10));

        ID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(59, 75, 82));
        ID.setText("Id:");
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        text_idVehiculo.setBorder(null);
        jPanel1.add(text_idVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 258, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 258, 10));

        Modelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Modelo.setForeground(new java.awt.Color(59, 75, 82));
        Modelo.setText("Modelo:");
        jPanel1.add(Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, 90, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, 310, 10));

        Marca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Marca.setForeground(new java.awt.Color(59, 75, 82));
        Marca.setText("Marca:");
        jPanel1.add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 70, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, 258, 10));

        CIlindrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CIlindrada.setForeground(new java.awt.Color(59, 75, 82));
        CIlindrada.setText("Cilindrada:");
        jPanel1.add(CIlindrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 670, 110, -1));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 730, 310, 10));

        text_valor.setBorder(null);
        jPanel1.add(text_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 800, 258, -1));

        Valor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Valor.setForeground(new java.awt.Color(59, 75, 82));
        Valor.setText("Valor:");
        jPanel1.add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 70, -1));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 820, 258, 10));

        jSeparator15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 483, 750, 10));

        datosDelVehiculo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        datosDelVehiculo1.setForeground(new java.awt.Color(59, 75, 82));
        datosDelVehiculo1.setText("Datos del Vehiculo");
        jPanel1.add(datosDelVehiculo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 219, -1));

        Color2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Color2.setForeground(new java.awt.Color(59, 75, 82));
        Color2.setText("Aire Acondicionado:");
        jPanel1.add(Color2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 940, -1, -1));

        obcionesAdicionales1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        obcionesAdicionales1.setForeground(new java.awt.Color(59, 75, 82));
        obcionesAdicionales1.setText("Entrega Vehiculo Usado");
        jPanel1.add(obcionesAdicionales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1110, 219, -1));

        FechaEntregaVehiculoUsado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FechaEntregaVehiculoUsado.setForeground(new java.awt.Color(59, 75, 82));
        FechaEntregaVehiculoUsado.setText("Fecha de Entrega:");
        jPanel1.add(FechaEntregaVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1430, 140, -1));

        aireAcondicionadoNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aireAcondicionadoNo.setText("NO");
        jPanel1.add(aireAcondicionadoNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 980, -1, -1));

        aireAcondicionadoSi2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aireAcondicionadoSi2.setText("SI");
        jPanel1.add(aireAcondicionadoSi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 980, -1, -1));

        jSeparator17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 850, 750, 10));

        tipoDePintura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoDePintura.setForeground(new java.awt.Color(59, 75, 82));
        tipoDePintura.setText("Pintura Metalizada:");
        jPanel1.add(tipoDePintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 940, 130, -1));

        obcionesAdicionales4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        obcionesAdicionales4.setForeground(new java.awt.Color(59, 75, 82));
        obcionesAdicionales4.setText("Obciones Adicionales");
        jPanel1.add(obcionesAdicionales4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 880, 219, -1));

        ModeloVehiculoUsado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ModeloVehiculoUsado.setForeground(new java.awt.Color(59, 75, 82));
        ModeloVehiculoUsado.setText("Modelo:");
        jPanel1.add(ModeloVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1270, 100, -1));

        modeloVehiculoUsado.setBorder(null);
        jPanel1.add(modeloVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1300, 310, -1));
        jPanel1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1320, 310, 10));

        MarcaVehiculoUsado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MarcaVehiculoUsado.setForeground(new java.awt.Color(59, 75, 82));
        MarcaVehiculoUsado.setText("Marca:");
        jPanel1.add(MarcaVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1180, 80, -1));

        marcaVehiculoUsado.setBorder(null);
        jPanel1.add(marcaVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1210, 258, -1));
        jPanel1.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1230, 258, 10));

        CIlindradaVehiculoUsado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CIlindradaVehiculoUsado.setForeground(new java.awt.Color(59, 75, 82));
        CIlindradaVehiculoUsado.setText("Cilindrada:");
        jPanel1.add(CIlindradaVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1270, 100, -1));

        cilindradaVehiculoUsado.setBorder(null);
        jPanel1.add(cilindradaVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1300, 310, -1));
        jPanel1.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1320, 310, 10));

        PrecioTasacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PrecioTasacion.setForeground(new java.awt.Color(59, 75, 82));
        PrecioTasacion.setText("Precio de Tasacion:");
        jPanel1.add(PrecioTasacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1340, 160, -1));

        precioTasacion.setBorder(null);
        jPanel1.add(precioTasacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1370, 258, -1));
        jPanel1.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1390, 258, 10));

        Matricula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Matricula.setForeground(new java.awt.Color(59, 75, 82));
        Matricula.setText("Matricula:");
        jPanel1.add(Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1180, 100, -1));

        matricula.setBorder(null);
        jPanel1.add(matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1210, 310, -1));
        jPanel1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1230, 310, 10));

        fechaEntrega.setBorder(null);
        jPanel1.add(fechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1460, 258, -1));
        jPanel1.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1480, 258, 10));

        FechaVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FechaVenta.setForeground(new java.awt.Color(59, 75, 82));
        FechaVenta.setText("Fecha de Venta:");
        jPanel1.add(FechaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1580, 140, -1));

        fechaEntrega1.setBorder(null);
        jPanel1.add(fechaEntrega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1610, 258, -1));
        jPanel1.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1630, 258, 10));

        jSeparator27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1080, 750, 10));

        Garantia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Garantia.setForeground(new java.awt.Color(59, 75, 82));
        Garantia.setText("Garantia:");
        jPanel1.add(Garantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1580, 140, -1));

        garantia.setBorder(null);
        jPanel1.add(garantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1610, 258, -1));
        jPanel1.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1630, 258, 10));

        buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(59, 75, 82));
        buscar.setText("Buscar:");
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 70, -1));

        text_buscar.setBorder(null);
        text_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(text_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 210, -1));
        jPanel1.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 220, 10));

        button_buscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\GitHub\\7502320048_Shein_moreno_POO-_2024_1\\7502320048_Shein_moreno_POO_ACT_1 _2024\\SheinMorenoAct1Poo20241\\src\\Interfaces\\iconos\\lupa.png")); // NOI18N
        button_buscar.setBorder(null);
        button_buscar.setBorderPainted(false);
        button_buscar.setContentAreaFilled(false);
        button_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(button_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        buscar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buscar1.setForeground(new java.awt.Color(59, 75, 82));
        buscar1.setText("Buscar:");
        jPanel1.add(buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 70, -1));
        jPanel1.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 220, 10));

        button_buscar2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\GitHub\\7502320048_Shein_moreno_POO-_2024_1\\7502320048_Shein_moreno_POO_ACT_1 _2024\\SheinMorenoAct1Poo20241\\src\\Interfaces\\iconos\\lupa.png")); // NOI18N
        button_buscar2.setBorder(null);
        button_buscar2.setBorderPainted(false);
        button_buscar2.setContentAreaFilled(false);
        button_buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_buscar2ActionPerformed(evt);
            }
        });
        jPanel1.add(button_buscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, -1));

        text_buscar1.setBorder(null);
        text_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_buscar1ActionPerformed(evt);
            }
        });
        jPanel1.add(text_buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 210, -1));

        comboBox_modelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "CAMARO SIX SS", "ONIX TURBO RS MT", "LOGAN LIFE", "SANDERO LIFE+" }));
        comboBox_modelo.setBorder(null);
        jPanel1.add(comboBox_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, 310, -1));

        comboBox_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "CHEVROLET", "RENAULT", " NISSAN", " MAZDA", " KIA", "TOYOTA", " VOLKSWAGEN", " SUZUKI", " FORD", " MERCEDES BENZ " }));
        comboBox_marca.setBorder(null);
        jPanel1.add(comboBox_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 250, -1));

        comboBox_cilindrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " (6.2L V8 SFI)", "(1.0T)", " (cm³) 1598)", " ", " " }));
        comboBox_cilindrada.setBorder(null);
        jPanel1.add(comboBox_cilindrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 700, 310, -1));

        pinturaMetalizadaSi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pinturaMetalizadaSi.setText("SI");
        jPanel1.add(pinturaMetalizadaSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 980, -1, -1));

        pinturaMetalizadaNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pinturaMetalizadaNo.setText("NO");
        jPanel1.add(pinturaMetalizadaNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 980, -1, -1));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\UNIVERSIDAD\\interfaz\\ventaDeVehiculos750,2000.png")); // NOI18N
        fondo.setOpaque(true);
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 2000));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearVentaActionPerformed

    private void text_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nombreActionPerformed

    private void text_celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_celularActionPerformed

    private void text_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_direccionActionPerformed

    private void text_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_apellidoActionPerformed

    private void text_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_buscarActionPerformed

    private void button_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_buscarActionPerformed

        botonBuscar();

    }//GEN-LAST:event_button_buscarActionPerformed

    private void button_buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_buscar2ActionPerformed
        
        botonBuscar2();
    }//GEN-LAST:event_button_buscar2ActionPerformed

    private void text_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_buscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_buscar1ActionPerformed
    private boolean botonBuscar() {

        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/plataforma", "root", "");
            PreparedStatement preparedStatement = connection.prepareStatement("select * from cliente where ID = ?");
            preparedStatement.setString(1, text_buscar.getText().trim());

            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                text_id.setText(resultSet.getString("ID"));
                text_nombre.setText(resultSet.getString("Nombre"));
                text_apellido.setText(resultSet.getString("Apellido"));
                text_celular.setText(resultSet.getString("Celular"));
                text_correoElectronico.setText(resultSet.getString("Correo"));
                text_direccion.setText(resultSet.getString("Direccion"));
                

            } else {
                JOptionPane.showMessageDialog(null, "Cliente no registrado");

            }

        } catch (Exception e) {

        }
        return false;
    }
    
    private boolean botonBuscar2() {

        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/plataforma", "root", "");
            PreparedStatement preparedStatement = connection.prepareStatement("select * from catalogo where ID = ?");
            preparedStatement.setString(1, text_buscar.getText().trim());

            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                text_idVehiculo.setText(resultSet.getString("ID"));
                comboBox_marca.setSelectedItem(resultSet.getString("Nombre"));
                comboBox_modelo.setSelectedItem(resultSet.getString("Apellido"));
                comboBox_cilindrada.setSelectedItem(resultSet.getString("Celular"));
                text_valor.setText(resultSet.getString("Correo"));
               
                

            } else {
                JOptionPane.showMessageDialog(null, "Automovil no registrado");

            }

        } catch (Exception e) {

        }
        return false;
    }

    

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel CIlindrada;
    private javax.swing.JLabel CIlindradaVehiculoUsado;
    private javax.swing.JLabel Celular;
    private javax.swing.JLabel Color2;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel FechaEntregaVehiculoUsado;
    private javax.swing.JLabel FechaVenta;
    private javax.swing.JLabel Garantia;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel MarcaVehiculoUsado;
    private javax.swing.JLabel Matricula;
    private javax.swing.JLabel Modelo;
    private javax.swing.JLabel ModeloVehiculoUsado;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel PrecioTasacion;
    private javax.swing.JLabel Valor;
    private javax.swing.JCheckBox aireAcondicionadoNo;
    private javax.swing.JCheckBox aireAcondicionadoSi2;
    private javax.swing.JLabel buscar;
    private javax.swing.JLabel buscar1;
    private javax.swing.JButton button_buscar;
    private javax.swing.JButton button_buscar2;
    private javax.swing.JTextField cilindradaVehiculoUsado;
    private javax.swing.JComboBox<String> comboBox_cilindrada;
    private javax.swing.JComboBox<String> comboBox_marca;
    private javax.swing.JComboBox<String> comboBox_modelo;
    private javax.swing.JButton crearVenta;
    private javax.swing.JLabel datosDelCliente;
    private javax.swing.JLabel datosDelVehiculo1;
    private javax.swing.JTextField fechaEntrega;
    private javax.swing.JTextField fechaEntrega1;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField garantia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField marcaVehiculoUsado;
    private javax.swing.JTextField matricula;
    private javax.swing.JTextField modeloVehiculoUsado;
    private javax.swing.JLabel nuevaVenta1;
    private javax.swing.JLabel obcionesAdicionales1;
    private javax.swing.JLabel obcionesAdicionales4;
    private javax.swing.JCheckBox pinturaMetalizadaNo;
    private javax.swing.JCheckBox pinturaMetalizadaSi;
    private javax.swing.JTextField precioTasacion;
    private javax.swing.JTextField text_apellido;
    private javax.swing.JTextField text_buscar;
    private javax.swing.JTextField text_buscar1;
    private javax.swing.JTextField text_celular;
    private javax.swing.JTextField text_correoElectronico;
    private javax.swing.JTextField text_direccion;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_idVehiculo;
    private javax.swing.JTextField text_nombre;
    private javax.swing.JTextField text_valor;
    private javax.swing.JLabel tipoDePintura;
    // End of variables declaration//GEN-END:variables
}
