/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.SwingUtilities;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class vendedorNuevoCliente extends javax.swing.JPanel {

    /**
     * Creates new form vendedorNuevoUsuario
     */
    public vendedorNuevoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nuevoCliente = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        apellido1 = new javax.swing.JLabel();
        celular1 = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        text_id = new javax.swing.JTextField();
        text_apellido = new javax.swing.JTextField();
        text_nombre = new javax.swing.JTextField();
        text_contraseña = new javax.swing.JTextField();
        text_celular = new javax.swing.JTextField();
        text_direccion = new javax.swing.JTextField();
        text_correoElectronico = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 596));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 525));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nuevoCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nuevoCliente.setForeground(new java.awt.Color(59, 75, 82));
        nuevoCliente.setText("Nuevo Cliente");
        jPanel2.add(nuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 6, 219, -1));

        id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        id.setForeground(new java.awt.Color(59, 75, 82));
        id.setText("Id:");
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 43, -1, -1));

        nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(59, 75, 82));
        nombre.setText("Nombres:");
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 121, -1, -1));

        correo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        correo.setForeground(new java.awt.Color(59, 75, 82));
        correo.setText("Correo:");
        jPanel2.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 121, 68, -1));

        apellido1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        apellido1.setForeground(new java.awt.Color(59, 75, 82));
        apellido1.setText("Apellidos:");
        jPanel2.add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, -1));

        celular1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        celular1.setForeground(new java.awt.Color(59, 75, 82));
        celular1.setText("Celular:");
        jPanel2.add(celular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 43, 63, -1));

        direccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        direccion.setForeground(new java.awt.Color(59, 75, 82));
        direccion.setText("Direccion:");
        jPanel2.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 295, 97, -1));

        contraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contraseña.setForeground(new java.awt.Color(59, 75, 82));
        contraseña.setText("Contraseña:");
        jPanel2.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 110, -1));

        jButton1.setBackground(new java.awt.Color(0, 150, 247));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Crear Usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 405, 354, 45));

        text_id.setBorder(null);
        jPanel2.add(text_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 69, 258, -1));

        text_apellido.setBorder(null);
        text_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_apellidoActionPerformed(evt);
            }
        });
        jPanel2.add(text_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 235, 260, -1));

        text_nombre.setBorder(null);
        text_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nombreActionPerformed(evt);
            }
        });
        jPanel2.add(text_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 147, 258, -1));

        text_contraseña.setBorder(null);
        jPanel2.add(text_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 279, -1));

        text_celular.setBorder(null);
        text_celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_celularActionPerformed(evt);
            }
        });
        jPanel2.add(text_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 69, 279, -1));

        text_direccion.setBorder(null);
        text_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_direccionActionPerformed(evt);
            }
        });
        jPanel2.add(text_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 333, 621, -1));

        text_correoElectronico.setBorder(null);
        jPanel2.add(text_correoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 147, 279, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 92, 258, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 169, 258, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 280, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 169, 279, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 91, 279, 11));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 355, 621, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 257, 260, 10));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\UNIVERSIDAD\\interfaz\\contentBlanco.png")); // NOI18N
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 530));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 525));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void text_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nombreActionPerformed

    private void text_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_apellidoActionPerformed

    private void text_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_direccionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/plataforma", "root", "");
            // Especifica las columnas en las que deseas insertar datos
            String sql = "INSERT INTO cliente (Nombre, Apellido, ID, Celular, Correo, Direccion, Rol, Contraseña) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement preparedStatementRegistrarUsuario = connection.prepareStatement(sql);

            // Asigna los valores a los parámetros
            preparedStatementRegistrarUsuario.setString(1, text_nombre.getText().trim());
            preparedStatementRegistrarUsuario.setString(2, text_apellido.getText().trim());
            preparedStatementRegistrarUsuario.setString(3, text_id.getText().trim());
            preparedStatementRegistrarUsuario.setString(4, text_celular.getText().trim());
            preparedStatementRegistrarUsuario.setString(5, text_correoElectronico.getText().trim());
            preparedStatementRegistrarUsuario.setString(6, text_direccion.getText().trim());
            preparedStatementRegistrarUsuario.setString(7, "cliente"); // Asegúrate que "cliente" es el valor correcto
            preparedStatementRegistrarUsuario.setString(8, text_contraseña.getText().trim());

            // Ejecuta la actualización
            preparedStatementRegistrarUsuario.executeUpdate();

            // Limpia los campos después de la inserción
            text_nombre.setText("");
            text_apellido.setText("");
            text_id.setText("");
            text_celular.setText("");
            text_correoElectronico.setText("");
            text_direccion.setText("");
            text_contraseña.setText("");

            // Muestra un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Registro Exitoso");

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al agregar nuevo cliente", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void text_celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_celularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido1;
    private javax.swing.JLabel celular1;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nuevoCliente;
    private javax.swing.JTextField text_apellido;
    private javax.swing.JTextField text_celular;
    private javax.swing.JTextField text_contraseña;
    private javax.swing.JTextField text_correoElectronico;
    private javax.swing.JTextField text_direccion;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_nombre;
    // End of variables declaration//GEN-END:variables
}
