/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class VendedorNuevaVenta extends javax.swing.JPanel {

    /**
     * Creates new form VentanaNuevaVenta
     */
    public VendedorNuevaVenta() {
       
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        datosDelCliente = new javax.swing.JLabel();
        dni1 = new javax.swing.JLabel();
        DNI = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Nombre = new javax.swing.JLabel();
        nombres = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Correo = new javax.swing.JLabel();
        correoElectronico = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Apellido = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Celular = new javax.swing.JLabel();
        celular = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Direccion = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        contraseña = new javax.swing.JLabel();
        contraseñaText = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        nuevaVenta1 = new javax.swing.JLabel();
        crearVenta = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        ID = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        Modelo = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        Marca = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        CIlindrada = new javax.swing.JLabel();
        cilindrada = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        Color = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        valor = new javax.swing.JTextField();
        Valor = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        datosDelVehiculo1 = new javax.swing.JLabel();
        Color1 = new javax.swing.JLabel();
        color1 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        Color2 = new javax.swing.JLabel();
        obcionesAdicionales1 = new javax.swing.JLabel();
        FechaEntregaVehiculoUsado = new javax.swing.JLabel();
        aireAcondicionadoNo = new javax.swing.JCheckBox();
        aireAcondicionadoSi2 = new javax.swing.JCheckBox();
        jSeparator17 = new javax.swing.JSeparator();
        obcionesAdicionales3 = new javax.swing.JLabel();
        obcionesAdicionales4 = new javax.swing.JLabel();
        IdVehiculoUsado = new javax.swing.JLabel();
        id1 = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        ModeloVehiculoUsado = new javax.swing.JLabel();
        modeloVehiculoUsado = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        MarcaVehiculoUsado = new javax.swing.JLabel();
        marcaVehiculoUsado = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        CIlindradaVehiculoUsado = new javax.swing.JLabel();
        cilindradaVehiculoUsado = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        ColorVehicculoUsado = new javax.swing.JLabel();
        colorVehiculoUsado = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        PrecioTasacion = new javax.swing.JLabel();
        precioTasacion = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        Matricula = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        fechaEntrega = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        FechaVenta = new javax.swing.JLabel();
        fechaEntrega1 = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        Garantia = new javax.swing.JLabel();
        garantia = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        fondo = new javax.swing.JLabel();

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datosDelCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        datosDelCliente.setForeground(new java.awt.Color(59, 75, 82));
        datosDelCliente.setText("Datos del Cliente");
        jPanel1.add(datosDelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 219, -1));

        dni1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dni1.setForeground(new java.awt.Color(59, 75, 82));
        dni1.setText("DNI:");
        jPanel1.add(dni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        DNI.setBorder(null);
        jPanel1.add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 258, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 258, 10));

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(59, 75, 82));
        Nombre.setText("Nombres:");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        nombres.setBorder(null);
        nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresActionPerformed(evt);
            }
        });
        jPanel1.add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 258, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 258, 10));

        Correo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Correo.setForeground(new java.awt.Color(59, 75, 82));
        Correo.setText("Correo:");
        jPanel1.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 68, -1));

        correoElectronico.setBorder(null);
        jPanel1.add(correoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 279, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 279, 10));

        Apellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Apellido.setForeground(new java.awt.Color(59, 75, 82));
        Apellido.setText("Apellidos:");
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, -1));

        apellido.setBorder(null);
        apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoActionPerformed(evt);
            }
        });
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 260, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 260, 10));

        Celular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Celular.setForeground(new java.awt.Color(59, 75, 82));
        Celular.setText("Celular:");
        jPanel1.add(Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 63, -1));

        celular.setBorder(null);
        celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularActionPerformed(evt);
            }
        });
        jPanel1.add(celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 279, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 279, 11));

        Direccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Direccion.setForeground(new java.awt.Color(59, 75, 82));
        Direccion.setText("Direccion:");
        jPanel1.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 97, -1));

        direccion.setBorder(null);
        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 621, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 621, 10));

        contraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contraseña.setForeground(new java.awt.Color(59, 75, 82));
        contraseña.setText("Contraseña:");
        jPanel1.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 110, -1));

        contraseñaText.setBorder(null);
        contraseñaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaTextActionPerformed(evt);
            }
        });
        jPanel1.add(contraseñaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 280, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 280, 10));

        nuevaVenta1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nuevaVenta1.setForeground(new java.awt.Color(59, 75, 82));
        nuevaVenta1.setText("Nueva venta");
        jPanel1.add(nuevaVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 219, -1));

        crearVenta.setBackground(new java.awt.Color(0, 150, 247));
        crearVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        crearVenta.setForeground(new java.awt.Color(255, 255, 255));
        crearVenta.setText("Crear Venta");
        crearVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearVentaActionPerformed(evt);
            }
        });
        jPanel1.add(crearVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1780, 354, 45));

        jSeparator8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1530, 750, 10));

        ID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(59, 75, 82));
        ID.setText("Id:");
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        id.setBorder(null);
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 258, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 258, 10));

        Modelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Modelo.setForeground(new java.awt.Color(59, 75, 82));
        Modelo.setText("Modelo:");
        jPanel1.add(Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, -1, -1));

        modelo.setBorder(null);
        jPanel1.add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 310, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 310, 10));

        Marca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Marca.setForeground(new java.awt.Color(59, 75, 82));
        Marca.setText("Marca:");
        jPanel1.add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, -1));

        marca.setBorder(null);
        jPanel1.add(marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 258, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, 258, 10));

        CIlindrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CIlindrada.setForeground(new java.awt.Color(59, 75, 82));
        CIlindrada.setText("Cilindrada:");
        jPanel1.add(CIlindrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 660, -1, -1));

        cilindrada.setBorder(null);
        jPanel1.add(cilindrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 690, 310, -1));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 710, 310, 10));

        Color.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Color.setForeground(new java.awt.Color(59, 75, 82));
        Color.setText("Color:");
        jPanel1.add(Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, -1, -1));

        color.setBorder(null);
        jPanel1.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, 258, -1));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 800, 258, 10));

        valor.setBorder(null);
        jPanel1.add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 780, 258, -1));

        Valor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Valor.setForeground(new java.awt.Color(59, 75, 82));
        Valor.setText("Valor:");
        jPanel1.add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 750, -1, -1));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 800, 258, 10));

        jSeparator15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 483, 750, 10));

        datosDelVehiculo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        datosDelVehiculo1.setForeground(new java.awt.Color(59, 75, 82));
        datosDelVehiculo1.setText("Datos del Vehiculo");
        jPanel1.add(datosDelVehiculo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 219, -1));

        Color1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Color1.setForeground(new java.awt.Color(59, 75, 82));
        Color1.setText("Color Pintura:");
        jPanel1.add(Color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 980, -1, -1));

        color1.setBorder(null);
        jPanel1.add(color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1010, 258, -1));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1030, 258, 10));

        Color2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Color2.setForeground(new java.awt.Color(59, 75, 82));
        Color2.setText("Aire Acondicionado:");
        jPanel1.add(Color2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 940, -1, -1));

        obcionesAdicionales1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        obcionesAdicionales1.setForeground(new java.awt.Color(59, 75, 82));
        obcionesAdicionales1.setText("Entrega Vehiculo Usado");
        jPanel1.add(obcionesAdicionales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1110, 219, -1));

        FechaEntregaVehiculoUsado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FechaEntregaVehiculoUsado.setForeground(new java.awt.Color(59, 75, 82));
        FechaEntregaVehiculoUsado.setText("Fecha de Entrega:");
        jPanel1.add(FechaEntregaVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1430, 140, -1));

        aireAcondicionadoNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aireAcondicionadoNo.setText("NO");
        jPanel1.add(aireAcondicionadoNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 990, -1, -1));

        aireAcondicionadoSi2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aireAcondicionadoSi2.setText("SI");
        jPanel1.add(aireAcondicionadoSi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 990, -1, -1));

        jSeparator17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 850, 750, 10));

        obcionesAdicionales3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        obcionesAdicionales3.setForeground(new java.awt.Color(59, 75, 82));
        obcionesAdicionales3.setText("Pintura Metalizada:");
        jPanel1.add(obcionesAdicionales3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 940, 130, -1));

        obcionesAdicionales4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        obcionesAdicionales4.setForeground(new java.awt.Color(59, 75, 82));
        obcionesAdicionales4.setText("Obciones Adicionales");
        jPanel1.add(obcionesAdicionales4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 880, 219, -1));

        IdVehiculoUsado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IdVehiculoUsado.setForeground(new java.awt.Color(59, 75, 82));
        IdVehiculoUsado.setText("Id:");
        jPanel1.add(IdVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1430, -1, -1));

        id1.setBorder(null);
        jPanel1.add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1460, 258, -1));
        jPanel1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1480, 258, 10));

        ModeloVehiculoUsado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ModeloVehiculoUsado.setForeground(new java.awt.Color(59, 75, 82));
        ModeloVehiculoUsado.setText("Modelo:");
        jPanel1.add(ModeloVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1180, -1, -1));

        modeloVehiculoUsado.setBorder(null);
        jPanel1.add(modeloVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1210, 310, -1));
        jPanel1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1230, 310, 10));

        MarcaVehiculoUsado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MarcaVehiculoUsado.setForeground(new java.awt.Color(59, 75, 82));
        MarcaVehiculoUsado.setText("Marca:");
        jPanel1.add(MarcaVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1270, -1, -1));

        marcaVehiculoUsado.setBorder(null);
        jPanel1.add(marcaVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1300, 258, -1));
        jPanel1.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1320, 258, 10));

        CIlindradaVehiculoUsado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CIlindradaVehiculoUsado.setForeground(new java.awt.Color(59, 75, 82));
        CIlindradaVehiculoUsado.setText("Cilindrada:");
        jPanel1.add(CIlindradaVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1270, -1, -1));

        cilindradaVehiculoUsado.setBorder(null);
        jPanel1.add(cilindradaVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1300, 310, -1));
        jPanel1.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1320, 310, 10));

        ColorVehicculoUsado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColorVehicculoUsado.setForeground(new java.awt.Color(59, 75, 82));
        ColorVehicculoUsado.setText("Color:");
        jPanel1.add(ColorVehicculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1360, -1, -1));

        colorVehiculoUsado.setBorder(null);
        jPanel1.add(colorVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1390, 258, -1));
        jPanel1.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1410, 258, 10));

        PrecioTasacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PrecioTasacion.setForeground(new java.awt.Color(59, 75, 82));
        PrecioTasacion.setText("Precio de Tasacion:");
        jPanel1.add(PrecioTasacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1360, -1, -1));

        precioTasacion.setBorder(null);
        jPanel1.add(precioTasacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1390, 258, -1));
        jPanel1.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1410, 258, 10));

        Matricula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Matricula.setForeground(new java.awt.Color(59, 75, 82));
        Matricula.setText("Matricula:");
        jPanel1.add(Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1180, -1, -1));

        matricula.setBorder(null);
        jPanel1.add(matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1210, 310, -1));
        jPanel1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 1230, 310, 10));

        fechaEntrega.setBorder(null);
        jPanel1.add(fechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1460, 258, -1));
        jPanel1.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1480, 258, 10));

        FechaVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FechaVenta.setForeground(new java.awt.Color(59, 75, 82));
        FechaVenta.setText("Fecha de Venta:");
        jPanel1.add(FechaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1580, 140, -1));

        fechaEntrega1.setBorder(null);
        jPanel1.add(fechaEntrega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1610, 258, -1));
        jPanel1.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1630, 258, 10));

        jSeparator27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1080, 750, 10));

        Garantia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Garantia.setForeground(new java.awt.Color(59, 75, 82));
        Garantia.setText("Garantia:");
        jPanel1.add(Garantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1580, 140, -1));

        garantia.setBorder(null);
        jPanel1.add(garantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1610, 258, -1));
        jPanel1.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1630, 258, 10));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\UNIVERSIDAD\\interfaz\\ventaDeVehiculos750,2000.png")); // NOI18N
        fondo.setOpaque(true);
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 2000));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearVentaActionPerformed

    private void contraseñaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaTextActionPerformed

    private void nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresActionPerformed

    private void celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularActionPerformed

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel CIlindrada;
    private javax.swing.JLabel CIlindradaVehiculoUsado;
    private javax.swing.JLabel Celular;
    private javax.swing.JLabel Color;
    private javax.swing.JLabel Color1;
    private javax.swing.JLabel Color2;
    private javax.swing.JLabel ColorVehicculoUsado;
    private javax.swing.JLabel Correo;
    private javax.swing.JTextField DNI;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel FechaEntregaVehiculoUsado;
    private javax.swing.JLabel FechaVenta;
    private javax.swing.JLabel Garantia;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel IdVehiculoUsado;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel MarcaVehiculoUsado;
    private javax.swing.JLabel Matricula;
    private javax.swing.JLabel Modelo;
    private javax.swing.JLabel ModeloVehiculoUsado;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel PrecioTasacion;
    private javax.swing.JLabel Valor;
    private javax.swing.JCheckBox aireAcondicionadoNo;
    private javax.swing.JCheckBox aireAcondicionadoSi2;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField celular;
    private javax.swing.JTextField cilindrada;
    private javax.swing.JTextField cilindradaVehiculoUsado;
    private javax.swing.JTextField color;
    private javax.swing.JTextField color1;
    private javax.swing.JTextField colorVehiculoUsado;
    private javax.swing.JLabel contraseña;
    private javax.swing.JTextField contraseñaText;
    private javax.swing.JTextField correoElectronico;
    private javax.swing.JButton crearVenta;
    private javax.swing.JLabel datosDelCliente;
    private javax.swing.JLabel datosDelVehiculo1;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel dni1;
    private javax.swing.JTextField fechaEntrega;
    private javax.swing.JTextField fechaEntrega1;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField garantia;
    private javax.swing.JTextField id;
    private javax.swing.JTextField id1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField marcaVehiculoUsado;
    private javax.swing.JTextField matricula;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField modeloVehiculoUsado;
    private javax.swing.JTextField nombres;
    private javax.swing.JLabel nuevaVenta1;
    private javax.swing.JLabel obcionesAdicionales1;
    private javax.swing.JLabel obcionesAdicionales3;
    private javax.swing.JLabel obcionesAdicionales4;
    private javax.swing.JTextField precioTasacion;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
