/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.BorderLayout;

/**
 *
 * @author ASUS
 */
public class ventanaVendedor extends javax.swing.JFrame {

    /**
     * Creates new form VentanaVendedor
     */
    public ventanaVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonUsuario = new javax.swing.JButton();
        buttonVenta = new javax.swing.JButton();
        buttonCatalogo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        itemBarraVertical = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setDoubleBuffered(false);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VENDEDOR");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, 40));

        buttonUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonUsuario.setForeground(new java.awt.Color(255, 255, 255));
        buttonUsuario.setText("Usuario");
        buttonUsuario.setBorder(null);
        buttonUsuario.setContentAreaFilled(false);
        buttonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(buttonUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 215, 50));

        buttonVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonVenta.setForeground(new java.awt.Color(255, 255, 255));
        buttonVenta.setText("Venta");
        buttonVenta.setBorder(null);
        buttonVenta.setContentAreaFilled(false);
        buttonVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVentaActionPerformed(evt);
            }
        });
        jPanel2.add(buttonVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 215, 50));

        buttonCatalogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonCatalogo.setForeground(new java.awt.Color(255, 255, 255));
        buttonCatalogo.setText("Catalogo");
        buttonCatalogo.setBorder(null);
        buttonCatalogo.setContentAreaFilled(false);
        buttonCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCatalogoActionPerformed(evt);
            }
        });
        jPanel2.add(buttonCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 215, 50));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\UNIVERSIDAD\\interfaz\\menuVertical.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        itemBarraVertical.setOpaque(false);
        itemBarraVertical.setPreferredSize(new java.awt.Dimension(750, 55));
        itemBarraVertical.setRequestFocusEnabled(false);

        javax.swing.GroupLayout itemBarraVerticalLayout = new javax.swing.GroupLayout(itemBarraVertical);
        itemBarraVertical.setLayout(itemBarraVerticalLayout);
        itemBarraVerticalLayout.setHorizontalGroup(
            itemBarraVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );
        itemBarraVerticalLayout.setVerticalGroup(
            itemBarraVerticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemBarraVertical, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemBarraVertical, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsuarioActionPerformed
        
        ItemUsuario usuario = new ItemUsuario();
        usuario.setSize(750, 600);
        usuario.setLocation(0, 0);
        
        itemBarraVertical.removeAll();
        itemBarraVertical.add(usuario,BorderLayout.CENTER);
        itemBarraVertical.revalidate();
        itemBarraVertical.repaint();
        
        
    }//GEN-LAST:event_buttonUsuarioActionPerformed

    private void buttonVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVentaActionPerformed
        
        
        ItemVenta venta = new ItemVenta();
        venta.setSize(750, 600);
        venta.setLocation(0, 0);
        
        itemBarraVertical.removeAll();
        itemBarraVertical.add(venta,BorderLayout.CENTER);
        itemBarraVertical.revalidate();
        itemBarraVertical.repaint();
    }//GEN-LAST:event_buttonVentaActionPerformed

    private void buttonCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCatalogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCatalogo;
    private javax.swing.JButton buttonUsuario;
    private javax.swing.JButton buttonVenta;
    private javax.swing.JPanel itemBarraVertical;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
