/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.SwingUtilities;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    ImagenFondo fondo = new ImagenFondo();

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        this.setContentPane(fondo);
        //setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1_fondo = new javax.swing.JPanel();
        jLabel1_inicioSesion = new javax.swing.JLabel();
        jLabel1_usuario = new javax.swing.JLabel();
        jLabel2_contraseña = new javax.swing.JLabel();
        textContraseña = new javax.swing.JPasswordField();
        textUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1_iniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1_fondo.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1_fondo.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1_fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1_fondo.setDoubleBuffered(false);
        jPanel1_fondo.setOpaque(false);

        jLabel1_inicioSesion.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1_inicioSesion.setForeground(new java.awt.Color(59, 75, 82));
        jLabel1_inicioSesion.setText("Inicio Sesion");

        jLabel1_usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1_usuario.setForeground(new java.awt.Color(59, 75, 82));
        jLabel1_usuario.setText("Usuario:");

        jLabel2_contraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2_contraseña.setForeground(new java.awt.Color(59, 75, 82));
        jLabel2_contraseña.setText("Contraseña:");

        textContraseña.setBorder(null);
        textContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textContraseñaMousePressed(evt);
            }
        });
        textContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContraseñaActionPerformed(evt);
            }
        });

        textUsuario.setBorder(null);
        textUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textUsuarioMousePressed(evt);
            }
        });
        textUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuarioActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                jSeparator2AncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jButton1_iniciar.setBackground(new java.awt.Color(0, 150, 247));
        jButton1_iniciar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1_iniciar.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_iniciar.setText("Iniciar");
        jButton1_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_iniciarMouseClicked(evt);
            }
        });
        jButton1_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_iniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_fondoLayout = new javax.swing.GroupLayout(jPanel1_fondo);
        jPanel1_fondo.setLayout(jPanel1_fondoLayout);
        jPanel1_fondoLayout.setHorizontalGroup(
            jPanel1_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_fondoLayout.createSequentialGroup()
                .addGroup(jPanel1_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1_fondoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton1_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1_fondoLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1_inicioSesion))
                    .addGroup(jPanel1_fondoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2_contraseña)
                            .addComponent(jLabel1_usuario)
                            .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(598, Short.MAX_VALUE))
        );
        jPanel1_fondoLayout.setVerticalGroup(
            jPanel1_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_fondoLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1_inicioSesion)
                .addGap(46, 46, 46)
                .addComponent(jLabel1_usuario)
                .addGap(28, 28, 28)
                .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2_contraseña)
                .addGap(22, 22, 22)
                .addComponent(textContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton1_iniciar)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuarioActionPerformed

    private void jSeparator2AncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jSeparator2AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jSeparator2AncestorMoved

    private void textUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textUsuarioMousePressed


    }//GEN-LAST:event_textUsuarioMousePressed

    private void textContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textContraseñaMousePressed


    }//GEN-LAST:event_textContraseñaMousePressed

    private void textContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textContraseñaActionPerformed

    private void jButton1_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_iniciarActionPerformed

    }//GEN-LAST:event_jButton1_iniciarActionPerformed

    private void jButton1_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_iniciarMouseClicked
        String tipoUsuario = validarLoginbd();

        if (tipoUsuario.equals("cliente")) {
            ventanaCliente abrir = new ventanaCliente();
            abrir.setVisible(true);
            this.setVisible(false);
        } else if (tipoUsuario.equals("vendedor")) {
            ventanaVendedor abrir = new ventanaVendedor();
            abrir.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Los Datos no son Válidos", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1_iniciarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    private String validarLoginbd() {
        String id = textUsuario.getText().trim();
        String contraseña = String.valueOf(textContraseña.getPassword()).trim();

        Connection connection = null;
        PreparedStatement preparedStatementCliente = null;
        PreparedStatement preparedStatementVendedor = null;
        ResultSet resultSetCliente = null;
        ResultSet resultSetVendedor = null;

        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost/plataforma", "root", "");

            // Consulta para la tabla 'cliente'
            String sqlCliente = "SELECT * FROM cliente WHERE ID=? AND Contraseña=?";
            preparedStatementCliente = connection.prepareStatement(sqlCliente);
            preparedStatementCliente.setString(1, id);
            preparedStatementCliente.setString(2, contraseña);
            resultSetCliente = preparedStatementCliente.executeQuery();

            if (resultSetCliente.next()) {
                return "cliente"; // Usuario y contraseña coinciden en 'cliente'
            }

            // Consulta para la tabla 'vendedor'
            String sqlVendedor = "SELECT * FROM vendedor WHERE ID=? AND Contraseña=?";
            preparedStatementVendedor = connection.prepareStatement(sqlVendedor);
            preparedStatementVendedor.setString(1, id);
            preparedStatementVendedor.setString(2, contraseña);
            resultSetVendedor = preparedStatementVendedor.executeQuery();

            if (resultSetVendedor.next()) {
                return "vendedor"; // Usuario y contraseña coinciden en 'vendedor'
            }

        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (resultSetCliente != null) {
                    resultSetCliente.close();
                }
                if (resultSetVendedor != null) {
                    resultSetVendedor.close();
                }
                if (preparedStatementCliente != null) {
                    preparedStatementCliente.close();
                }
                if (preparedStatementVendedor != null) {
                    preparedStatementVendedor.close();
                }
                if (connection != null) {
                    connection.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        return "invalido"; // Usuario o contraseña no coinciden en ninguna tabla
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_iniciar;
    private javax.swing.JLabel jLabel1_inicioSesion;
    private javax.swing.JLabel jLabel1_usuario;
    private javax.swing.JLabel jLabel2_contraseña;
    private javax.swing.JPanel jPanel1_fondo;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField textContraseña;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables

    class ImagenFondo extends JPanel {
        //Atributos

        private Image imagen;
        //METODOS

        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("fondoLogin2.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);

        }
    }

}
