/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

/**
 *
 * @author ASUS
 */
public class ventanaPagoEnLinea extends javax.swing.JPanel {

    /**
     * Creates new form ventanaPagoEnLinea
     */
    public ventanaPagoEnLinea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        nuevaVenta1 = new javax.swing.JLabel();
        datosDelCliente = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        text_id = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Nombre = new javax.swing.JLabel();
        text_nombre = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Celular = new javax.swing.JLabel();
        text_celular = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Correo = new javax.swing.JLabel();
        text_correoElectronico = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        Direccion = new javax.swing.JLabel();
        text_direccion = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        text_apellido = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Apellido = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Modelo = new javax.swing.JLabel();
        CIlindrada = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        Marca = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        Valor = new javax.swing.JLabel();
        text_valor = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        datosDelVehiculo1 = new javax.swing.JLabel();
        CIlindrada1 = new javax.swing.JLabel();
        text_tipoMantenimiento = new javax.swing.JTextField();
        text_modelo = new javax.swing.JTextField();
        text_cilindrada = new javax.swing.JTextField();
        text_marca = new javax.swing.JTextField();
        text_descripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nuevaVenta1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nuevaVenta1.setForeground(new java.awt.Color(59, 75, 82));
        nuevaVenta1.setText("Pago en Linea");
        jPanel1.add(nuevaVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 219, -1));

        datosDelCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        datosDelCliente.setForeground(new java.awt.Color(59, 75, 82));
        datosDelCliente.setText("Datos del Cliente");
        jPanel1.add(datosDelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 219, -1));

        Id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Id.setForeground(new java.awt.Color(59, 75, 82));
        Id.setText("Id:");
        jPanel1.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        text_id.setBorder(null);
        jPanel1.add(text_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 258, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 258, 10));

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(59, 75, 82));
        Nombre.setText("Nombres:");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, -1));

        text_nombre.setBorder(null);
        text_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(text_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 258, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 258, 10));

        Celular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Celular.setForeground(new java.awt.Color(59, 75, 82));
        Celular.setText("Celular:");
        jPanel1.add(Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 63, -1));

        text_celular.setBorder(null);
        text_celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_celularActionPerformed(evt);
            }
        });
        jPanel1.add(text_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 279, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 279, 11));

        Correo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Correo.setForeground(new java.awt.Color(59, 75, 82));
        Correo.setText("Correo:");
        jPanel1.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 68, -1));

        text_correoElectronico.setBorder(null);
        jPanel1.add(text_correoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 279, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 279, 10));

        Direccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Direccion.setForeground(new java.awt.Color(59, 75, 82));
        Direccion.setText("Direccion:");
        jPanel1.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 97, -1));

        text_direccion.setBorder(null);
        text_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_direccionActionPerformed(evt);
            }
        });
        jPanel1.add(text_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 270, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 270, 10));

        text_apellido.setBorder(null);
        text_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_apellidoActionPerformed(evt);
            }
        });
        jPanel1.add(text_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 260, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 260, 10));

        Apellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Apellido.setForeground(new java.awt.Color(59, 75, 82));
        Apellido.setText("Apellidos:");
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 750, 20));

        Modelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Modelo.setForeground(new java.awt.Color(59, 75, 82));
        Modelo.setText("Modelo:");
        jPanel1.add(Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 90, -1));

        CIlindrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CIlindrada.setForeground(new java.awt.Color(59, 75, 82));
        CIlindrada.setText("Cilindrada:");
        jPanel1.add(CIlindrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 110, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 310, 10));

        Marca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Marca.setForeground(new java.awt.Color(59, 75, 82));
        Marca.setText("Marca:");
        jPanel1.add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 70, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 310, 10));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 310, 10));

        Valor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Valor.setForeground(new java.awt.Color(59, 75, 82));
        Valor.setText("Valor:");
        jPanel1.add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, 70, -1));

        text_valor.setBorder(null);
        jPanel1.add(text_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 780, 258, -1));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 800, 258, 10));

        datosDelVehiculo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        datosDelVehiculo1.setForeground(new java.awt.Color(59, 75, 82));
        datosDelVehiculo1.setText("Datos del Vehiculo");
        jPanel1.add(datosDelVehiculo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 219, -1));

        CIlindrada1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CIlindrada1.setForeground(new java.awt.Color(59, 75, 82));
        CIlindrada1.setText("Tipo de Mantenimiento:");
        jPanel1.add(CIlindrada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 190, -1));

        text_tipoMantenimiento.setBorder(null);
        jPanel1.add(text_tipoMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 310, -1));

        text_modelo.setBorder(null);
        jPanel1.add(text_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 310, -1));

        text_cilindrada.setBorder(null);
        jPanel1.add(text_cilindrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 310, -1));

        text_marca.setBorder(null);
        jPanel1.add(text_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 310, -1));

        text_descripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        text_descripcion.setForeground(new java.awt.Color(59, 75, 82));
        text_descripcion.setText("Descripcion:");
        jPanel1.add(text_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 190, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 680, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void text_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nombreActionPerformed

    private void text_celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_celularActionPerformed

    private void text_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_direccionActionPerformed

    private void text_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_apellidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel CIlindrada;
    private javax.swing.JLabel CIlindrada1;
    private javax.swing.JLabel Celular;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel Modelo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Valor;
    private javax.swing.JLabel datosDelCliente;
    private javax.swing.JLabel datosDelVehiculo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel nuevaVenta1;
    private javax.swing.JTextField text_apellido;
    private javax.swing.JTextField text_celular;
    private javax.swing.JTextField text_cilindrada;
    private javax.swing.JTextField text_correoElectronico;
    private javax.swing.JLabel text_descripcion;
    private javax.swing.JTextField text_direccion;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_marca;
    private javax.swing.JTextField text_modelo;
    private javax.swing.JTextField text_nombre;
    private javax.swing.JTextField text_tipoMantenimiento;
    private javax.swing.JTextField text_valor;
    // End of variables declaration//GEN-END:variables
}
